### ISSUE TITLE
[Enhancement] Replace `save__init__args` with `@dataclass`?

### ISSUE THREAD

**Issue by neighthan** [astooke/rlpyt#1]
In `ppo.py`, for example (I assume this is used in other classes as well), `save__init__args` is used to save all passed arguments as instance attributes. I assume this is just to avoid having to say `self.x = x` several times? (and also reduces the need to update code in two places if a new argument is added). Given that `rlpyt` already expects Python 3.7, is there a reason you prefer this method over using `@dataclass`? If you're not familiar with them (they're new in 3.7) [dataclasses] can automatically create a handful of methods for you to handle cases just like this one (where you need to assign several attributes at `__init__`). E.g. you could replace

```python
class A:
    def __init__(self, x: int, y: float, z: str = "0"):
        self.x = x
        self.y = y
        self.z = z
```

with 

```python
from dataclasses import dataclass

@dataclass
class A:
    x: int
    y: float
    z: str = "0"
```

`@dataclass` will also create `__eq__` and `__repr__` methods by default, though these are easy to turn off. There are also hooks if you want it to build an `__init__` method for you but then do some other things in `__init__` yourself.

I haven't taken a look at other classes where `save__init__args` is used, but if the usage is generally like in `PPO`, I think this replacement would be easy; happy to submit a PR if you're interested. (I think `@dataclass` could be nicer because 1) it seems that `save__init__args` is easier to make a mistake with (e.g. has to be called before `super().__init__()`) and 2) Python tooling will recognize attributes better (e.g. right now, my VS Code complains that all attributes of PPO don't exist; it can't track them being assigned using `setattr`. So there's less support for autocompletion / typing).

[dataclasses]: https://docs.python.org/3/library/dataclasses.html

**Comment by neighthan** [comment]
After looking at `AtariEnv`, I'm not sure if this would be a good change; if `underscore=True`, there's not a good way with dataclasses to change all of the class attribute names to be "_"-prefixed versions of the arguments passed to `__init__`.

**Comment by astooke** [comment]
Yes I thought a little bit about using data classes, but they seemed slightly off-topic for just saving args to init.  It would probably work and not be that different, but I'm inclined to keep as is:
Using `save__init__args`, it's more clear that this is all that is happening.  You're free to call it before or after `super().__init__` by using the `overwrite` keyword to control behavior for kwargs which both classes see.  And see the other kwargs for other options like saving only the sub-class kwargs.  I haven't looked closely at how data classes work as subclasses. 

But the question of programming tools interpreting attributes seems useful!  Will keep this open to see if it can be improved...?

**Comment by astooke** [comment]
Without any movement on this in a long time, closing.  But please reopen if new ideas come up e.g. about type hints!
