### ISSUE TITLE
Iterating through namedarrytuple

### ISSUE THREAD

**Issue by ankeshanand** [astooke/rlpyt#100]
Iterating through `namedarraytuple` currently behaves as iterating through the underlying tuple. I think the desired behavior should be iterating through the underlying array instead? I can write a custom iterator to get around this, but I was wondering if the behavior is intended.

**Comment by astooke** [comment]
Hi!  This is the intended behavior, which is the same as what happens for a `namedtuple`.  Although, I think I see what you mean, iterating through a `namedarraytuple` could instead provide iterates which are `namedarraytuples` of the same structure, but containing arrays which are the iterate elements along the leading dimension.  Is this what you're looking for?

It is important to preserve some way to access the fields in order...a lot of the methods depend on being able to loop through the entries easily as ``[for s in self]``.  And for simplicity, it keeps the interface closer to `namedtuple` / `tuple`.

But if this is a use case, it could be great to add another method which does iterate the way stated above.  Want to post here what you come up with for that and I'll try to work it in?

**Comment by astooke** [comment]
Not planning any changes here, but if you come up with something that seems useful, please reopen!  :)
