### ISSUE TITLE
In-memory deep copy

### ISSUE THREAD

**Issue by jordan-schneider** [astooke/rlpyt#103]
Is there a way to do an in-memory deep copy of an algorithm (and associated agent, models, etc)?

I know I can get the state_dict and optim_state_dict, but I'm not sure how to create new objects to load those into without the constructor values for the algorithm, which I don't necessarily have.

**Comment by jordan-schneider** [comment]
Using the state_dict and optim_state dict copies the model weights correctly, but I can't do learning on the copy for some reason. Minimal code example below
```python
import logging

import torch

from rlpyt.agents.qpg.sac_agent import SacAgent
from rlpyt.algos.qpg.sac import SAC
from rlpyt.envs.gym import make as gym_make
from rlpyt.runners.minibatch_rl import MinibatchRl, MinibatchRlBase
from rlpyt.samplers.serial.sampler import SerialSampler


def main():
    n_steps = 1000

    sampler_kwargs = {
        "EnvCls": gym_make,
        "env_kwargs": {"id": "Hopper-v3"},
        "eval_env_kwargs": {"id": "Hopper-v3"},
        "batch_T": n_steps,
        "batch_B": 1,
        "max_decorrelation_steps": 0,
    }
    sampler = SerialSampler(**sampler_kwargs)

    algo_kwargs = {
        "batch_size": n_steps,
    }
    algo = SAC(**algo_kwargs)

    agent = SacAgent()

    runner = MinibatchRlBase(sampler=sampler, algo=algo, agent=agent, n_steps=n_steps)
    runner.startup()

    other_sampler = SerialSampler(**sampler_kwargs)
    model_state_dict = algo.agent.state_dict()
    other_agent = SacAgent(initial_model_state_dict=model_state_dict)

    other_algo = SAC(**algo_kwargs, initial_optim_state_dict=algo.optim_state_dict(),)

    other_runner = MinibatchRl(
        algo=other_algo,
        agent=other_agent,
        sampler=other_sampler,
        n_steps=n_steps,
        log_interval_steps=n_steps,
    )

    other_runner.startup()

    logging.error(f"agent pre train={agent.state_dict()}")

    other_runner.train()

    logging.error(f"agent={agent.state_dict()}")
    logging.error(f"other_agent={other_agent.state_dict()}")


if __name__ == "__main__":
    main()
```

I all three logging statements return the same values, even though training should have changed the weights of other_agent. I also know that its not just pointing to the same memory and changing both, as the first agent has the same weights before and after training.

I couldn't figure out a way to directly compare the state dicts, sorry about that.

**Comment by astooke** [comment]
OK glad that works!  I haven't considered the case of having multiple instances open of these classes, but it looks to be working.  Thanks for posting :)
