### ISSUE TITLE
Model-based Algorithm Implementation

### ISSUE THREAD

**Issue by jaztsong** [astooke/rlpyt#108]
Hello,

I'm attempting to adapt this lib for my model-based RL research, like **PILCO**.

I wonder, given the current architecture of this code, could it be difficult to integrate model-based algorithms into this repo?

Thank you in advance.

**Comment by astooke** [comment]
Hi!  I haven't yet implemented model-based algorithms myself, so maybe someone else who has could provide a better answer?

But I could see it fitting in smoothly, with everything model-based happening inside the algorithm's `optimize_agent()` method.  You could keep the rest of rlpyt the same, which inputs the "real" samples there, and then inside `optimize_agent()`, have it use the "real" samples to train the model(s), and have an inner loop where the model(s) is used to train the behavior policy.  

Does that sound about right?

**Comment by jaztsong** [comment]
Thanks for the prompt response. That sounds legit. To obtain the "real" samples, do I just obtain_samples from a simple serial sampler?

BTW, the code base seems missing the function of re-training/re-using previous stored models. I wonder if that's something incoming.

**Comment by astooke** [comment]
That’s right, to use obtain_samples of the sampler.

In the agents, there are keyword arguments like ‘initial_model_state_dict’, and this is where you could start with saved model parameters.  I don’t think there’s a posted example of this yet.

**Comment by DanielTakeshi** [comment]
@jaztsong  Have you seen these:

https://github.com/astooke/rlpyt/issues/69
https://github.com/astooke/rlpyt/issues/69

**Comment by astooke** [comment]
Hi @jaztsong did this end up working for you?

**Comment by jaztsong** [comment]
Thank you for your help. I forgot to close this issue.

I have successfully added a crude GP-based model-based algorithm. It can run now, but the policy network doesn't converge for now. Debugging...
