### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by thunanguyen** [astooke/rlpyt#11]
I compile the code in Window 10 and when I run the provided example, it keeps telling me this error: OSError: [WinError 126] The specified module could not be found

**Comment by thunanguyen** [comment]
Hi, sorry for my not replying back as I was busy with tons of exams. But now I am able to use rlpyt to run all examples except some use the command "cat /proc/cpuinfo | grep "physical id" | sort -u | wc -l", which is obviously Linux-only. I rarely use Linux, so can you explain what the command do and is there any alternatives for Window ?

**Comment by astooke** [comment]
Yes, that line simply tried to figure out the number of CPU sockets in your machine.  Most likely the answer is 1, and even if that's not right, you can still use 1 with good results.

**Comment by astooke** [comment]
Considering this solved, but please reopen if not.  :)
