### ISSUE TITLE
Mismatch in build_cpu_affinity args

### ISSUE THREAD

**Issue by vuoristo** [astooke/rlpyt#121]
https://github.com/astooke/rlpyt/blob/35af87255465b3644747294f7fd1ff6045dab910/rlpyt/utils/launching/affinity.py#L265

The args list of the actual `build_cpu_affinity` is
`build_cpu_affinity(slt, cpu, cpr, cpw=1, hto=None, res=0, skt=1, gpu=0, alt=0, saf=1)`,
which has the extra `gpu` argument in between `skt` and `alt` compared to the call.

On my machine this affinity code
```
affinity_code = encode_affinity(
    n_cpu_core=20,
    n_gpu=4,
    contexts_per_gpu=5,
    alternating=True,
)
```

fails the assertion
https://github.com/astooke/rlpyt/blob/35af87255465b3644747294f7fd1ff6045dab910/rlpyt/utils/launching/affinity.py#L218
due to the `alt` variable being passed into `gpu` argument.

**Comment by astooke** [comment]
Oops forgot to mention...fixed in commit 37e0ed0  .  Thanks!
