### ISSUE TITLE
Crashes when trying to log non JSON serializable data

### ISSUE THREAD

**Issue by mwilliammyers** [astooke/rlpyt#129]
Currently if you attempt to pass a `log_params` that is not JSON serializable  to `logger_context()`, we get an exception and the program crashes.

I could open a PR to fix this by changing [context.py#L73](https://github.com/astooke/rlpyt/blob/37e0ed0a17dc5264eed77fb577a890bdfa448952/rlpyt/utils/logging/context.py#L73) to something like:
```python
json.dump(log_params, f, skipkeys=True, default=lambda o: type(o).__name__)
```

if we want to protect against this and not make the caller sanitize input...

\*this only works for python3, but in my opinion python2 is dead 🙃

**Comment by astooke** [comment]
Ok yes great idea!  I had this problem before and just resorted to making all the config entries strings and converting in the train script, but much better to let the keys be more objects.
