### ISSUE TITLE
python executable hardcoded in launch_experiment

### ISSUE THREAD

**Issue by mwilliammyers** [astooke/rlpyt#130]
Thanks for such a useful library!

[exp_launcher.py#L46](https://github.com/astooke/rlpyt/blob/37e0ed0/rlpyt/utils/launching/exp_launcher.py#L46):

```python
call_list += ["python", script, slot_affinity_code, log_dir, str(run_ID)]
```

Assuming this library requires `>=python3.7` like the conda env files indicate; this will not work out of the box on macOS, Ubuntu and many other distros not using virtualenv/conda (or any other system that links `python` to `python3`).

I propose:
- adding an optional `python_executable` param to `launch_experiment()`
 - default the param to [`sys.executable`](https://docs.python.org/3/library/sys.html#sys.executable)
-  fallback to `"python"`.

I have a PR ready for this if it is the direction we want to go with.

**Comment by astooke** [comment]
Thanks!!  :)

OK hadn't considered this case, sounds like a good idea for a PR.

Hmm I guess I've always used rlpyt within a conda environment, and looks like now on Ubuntu18 outside of any conda env, my `python` is already the same as `python3`, lucky me.  One day python2 will go away hehe.
