### ISSUE TITLE
Test phase on custom environment

### ISSUE THREAD

**Issue by LecJackS** [astooke/rlpyt#157]
Hi,

I'm experimenting with a custom env on rlpyt. I've the intention to use different data for training and testing (env shows novel states on testing/evaluation vs training).

I have been using `example_1` as stepping stone, so far so good, but I'm not sure how to achieve this last bit: testing.

After running `runner.train()` (as in `example_1`, inside the logger), I think I should use `runner.evaluate_agent()` inside a loop to evaluate the agent several times (or maybe use `eval_max_steps=NumEvals` as SerialSampler argument?).

But I'm a bit (more) lost on how to "send" the **test** signal to my environment from here, as only the SerialSampler 'knows' where the environtment class is, and I cannot find a way to use it to send some arguments to the env in this phase.

In short (I don't know if i'm being clear) I need to know how:
1. to test/eval my agent
2. to send a "test" argument to my custom env on testing phase

Thank you!

**Comment by LecJackS** [comment]
Another alternative is to, at the end of training, save NN weights, and run **another** piece of code to load those weights into a new instance of the model that uses the environment with test data.

**Comment by astooke** [comment]
Actually the evaluation is performed using a separate instance of your environment, and this can be instantiated using different kwargs than the environment used for training.  See `env_kwargs` and `eval_env_kwargs` into the sampler.  Sounds like exactly what you need. :) 

https://github.com/astooke/rlpyt/blob/85d4e018a919118c6e42fac3e897aa346d84b9c5/examples/example_1.py#L29

Thanks for moving your question over!

**Comment by LecJackS** [comment]
Thank you very much for your fast reply! It worked perfectly!

I didn't understand correctly the eval process in between training before (expected some evaluation at the end of it).

So as if my past self read this:
* **While** training, evaluation is performed on `eval_n_envs` instances, `eval_max_steps` steps, and `eval_max_trajectories` as the "number of games to be played" by the agent in the evaluation phase.

* Also, what we see logged on tensorboard, is the evaluation process while training, and not the training itself.

On a related matter, is there a way to log ALSO the training process? so i can compare plots from training and testing .

**Comment by kargarisaac** [comment]
@LecJackS 
I think if you use `MinibatchRlEval()` the results you see in tensorboard are for evaluation. I think you can check `MinibatchRl()`. It doesn't have evaluation phase. So the results should be for training as mentioned in the documentation [here](https://rlpyt.readthedocs.io/en/latest/pages/runner.html?highlight=MinibatchRlEval#rlpyt.runners.minibatch_rl.MinibatchRl). It tracks performance online using learning trajectories, while in `MinibatchRlEval()`, it tracks performance offline using evaluation trajectories.
For evaluation, I use a function like this:
```
def evaluate(pre_trained_model):

    data = torch.load(pre_trained_model)
    agent_state_dict = data['agent_state_dict']['model']

    env = MyEnv()

    agent = MyAgent(
        initial_model_state_dict=agent_state_dict,
        model_kwargs=config["model_kwargs"],
        **config["agent"]
    )
    env_spaces = EnvSpaces(
            observation=env.observation_space,
            action=env.action_space,
    )
    agent.initialize(env_spaces)
    agent.eval_mode(0)

    obs = env.reset()
    prev_action = torch.tensor(0.0, dtype=torch.float) #None
    prev_reward = torch.tensor(0.0, dtype=torch.float) #None
    while True:
        agent_step = agent.step(torch.tensor(obs, dtype=torch.float32), prev_action, prev_reward)
        action = np.array(agent_step.agent_info.dist_info.mean)
        obs, reward, done, info = env.step(action)
        prev_action = torch.tensor(action, dtype=torch.float)
        prev_reward = torch.tensor(reward, dtype=torch.float)
        env.render()
        if done:
            obs = env.reset()
            prev_action = torch.tensor(0.0, dtype=torch.float)  # None
            prev_reward = torch.tensor(0.0, dtype=torch.float)  # None
            agent.reset()
```

**Comment by LecJackS** [comment]
Just for the record ended up solving the last issue like this:

Keep track of episode number on each environment instance (pass log interval as parameters).
Define summary writer, and log from environment on each test call, and last 50 train runs before calling to test.

     writer = SummaryWriter()
     epi_len = 65 # Episode number of steps
     log_int = 500 * epi_len

    sampler = SerialSampler(
        EnvCls=CustomEnv,
        env_kwargs=dict(id=env_id, mode="train", writer=writer, logInt=log_int),
        eval_env_kwargs=dict(id=env_id, mode="test", writer=writer, logInt=log_int),

And in the environment:

```
def plot_stats(self, reward):
        # Tensorboard debugging
        if self.mode =='test':
            # Plot all rewards
            self.writer.add_scalars('data/'+str(self.mode), {'reward': reward},
                                                             self.episode)
            # Save last numEvals for statistics
            self.rewardHist[self.numLog%self.numEvals] = reward

            if ((self.episode+1) % self.epiLogInt) == 0:
                # Plot statistics of last self.numEvals
                self.writer.add_scalars('data/'+str(self.mode),
                                    {'mean':   np.mean(self.rewardHist),
                                     'median': np.median(self.rewardHist),
                                     'max':    np.max(self.rewardHist),
                                     'min':    np.min(self.rewardHist)},
                                     self.episode)
                self.writer.add_scalars('data/'+str(self.mode)+"/",
                                            {'std': np.std(self.rewardHist)},
                                             self.episode)
                # Keep same count as training episodes
                self.episode += self.epiLogInt - 1 #self.numEvals
            self.numLog += 1
        else:
            # Want 5 training episodes before the 5 testing episodes
            if self.episode > (self.episode-self.numEvals-1) \
                and ((self.episode-self.numEvals) % self.epiLogInt) >= 0 \
                and ((self.episode-self.numEvals) % self.epiLogInt) < self.numEvals:
                # Plot all rewards
                #self.writer.add_scalars('data/'+str(self.mode), {'reward': reward},
                #                                                 self.episode)
                # Save last numEvals for statistics
                self.rewardHist[self.numLog%self.numEvals] = reward
                # Plot statistics of last self.numEvals
                if (self.numLog%self.numEvals) == (self.numEvals-1):
                    self.writer.add_scalars('data/'+str(self.mode),
                                            {'mean': np.mean(self.rewardHist),
                                             'median': np.median(self.rewardHist),
                                             'max': np.max(self.rewardHist),
                                             'min': np.min(self.rewardHist),
                                             'maxAllTime': self.maxRecord},
                                             self.episode)
                    self.writer.add_scalars('data/'+str(self.mode)+"/",
                                            {'std': np.std(self.rewardHist)},
                                             self.episode)
                self.numLog += 1
```

Ugly as f*ck, but it works, so I'm closing this issue :)
