### ISSUE TITLE
Unable to log to log_dir

### ISSUE THREAD

**Issue by kaixin96** [astooke/rlpyt#16]
May I ask why we need line 26-29 in `rlpyt.utils.logging.context`? It seems the log_dir argument takes effect only when it is same as LOG_DIR. However, I couldn't figure out why you set LOG_DIR as `osp.abspath(osp.join(osp.dirname(__file__), '../../../data'))`.

Thank you.

**Comment by astooke** [comment]
Yes those lines are supposed to force the logging to go into `rlpyt/data/[yyyymmdd]`.  The data folder is in the gitignore, and organizing experiments by date was just a personal preference.  So you can give it an experiment directory of `my_first_exp` and it will automatically move it to `rlpyt/data/[yyyymmdd]/my_first_exp/`.  

Of course you can change this to whatever you prefer. :)

Hope that helps!

**Comment by kaixin96** [comment]
Thanks for your clarification!
