### ISSUE TITLE
PPO RNN rnn_state not propagated

### ISSUE THREAD

**Issue by petrikvladimir** [astooke/rlpyt#166]
Hi, I am trying to understand LSTM training with PPO. It seems that optimizer uses rnn_state at time 0 to compute distribution for all timesteps:
`init_rnn_state = samples.agent.agent_info.prev_rnn_state[0]  # T=0.`

Other rnn_states are never used. In my understanding, the policy distribution should depend on rnn state, is that correct?

Can it be a reason for unsuccessful training in #85 ?

**Comment by petrikvladimir** [comment]
My understanding was wrong. RNN predicts the states from the initial state only (that is None by default). The collected RNN hidden states are thus ignored during agent optimization.

**Comment by astooke** [comment]
If your training trajectory starts in the middle of an episode, it should initialize with the saved RNN state from the first step of the sequence, and then use the newly-computed RNN states for all subsequent steps.  :)
