### ISSUE TITLE
"Name clash in Globals: info"

### ISSUE THREAD

**Issue by jordan-schneider** [astooke/rlpyt#168]
I'm trying to write tests for my code, and different tests use different gym environments. Because the GymEnvWrapper exports the transition info dict to the global namespace, when I get to the second test environment in the same file, https://github.com/astooke/rlpyt/blob/ca6483323c1ec372e9b4ec0ecde47bba620391d8/rlpyt/envs/gym.py#L104 is raised. Is there a way this could be avoided? I'd be happy with tuple overwrite behavior (perhaps in an optional flag in BaseSampler). Alternatively, if I had a way to manually clear the global namespace within the rlpyt package would also work.

**Comment by astooke** [comment]
Right!  This is a shortcoming of that globals approach, in that each file can only hold one environment...sorry about that.

A perfectly functioning alternative is to use the gym_schema wrapper: https://github.com/astooke/rlpyt/blob/master/rlpyt/envs/gym_schema.py  Basically, anywhere a `namedarraytuple` was defined, it's replaced by `NamedArrayTupleSchema`. This was written for the purpose of avoiding these kinds of difficulties that come with `namedtuples` and `namedarraytuples` being full on classes defined dynamically.

Does that solve it?

**Comment by jordan-schneider** [comment]
Yup, that fixes things. Thanks!
