### ISSUE TITLE
SerialEvalCollector gets the first action with all zeros observation

### ISSUE THREAD

**Issue by vuoristo** [astooke/rlpyt#17]
https://github.com/astooke/rlpyt/blob/15055b4daf6ab47b51a6fa682a9909f1167fc668/rlpyt/samplers/serial/collectors.py#L32

`SerialEvalCollector` is used in the examples to evaluate the algorithm. In the `collect_evaluation` method, environments are first reset and then the initial observations are turned into `namedarraytuple`s using `buffer_from_example`. In `buffer_from_example`, new numpy arrays are constructed for each element in the observation using either `np.zeros` or `np_mp_array`. The original values of the first observations in the evaluation trajectory are never copied into the buffers, which results in the first action getting computed using an all zeros observation.

**Comment by astooke** [comment]
Good catch!  Just fixed that in the `SerialEvalCollector` and the `CpuEvalCollector`.  `GpuEvalCollector` was already good.  Thanks!!

**Comment by vuoristo** [comment]
Sweet, that fixes it.
