### ISSUE TITLE
[question] OpenAI Gym Env?

### ISSUE THREAD

**Issue by jarlva** [astooke/rlpyt#170]
Hi,
Is it possible to use with OpenAI Gym Env (non-image like Cartpole - yes I know it's very basic but I have a custom one, similar to Cartpole, that can take a while to solve on a single machine)? If yes, can you please suggest how-to?

Is it possible to use in Windows10 (with Nvidia GPU)?

Thanks!

**Comment by LecJackS** [comment]
Try to search for "custom environment" on the issues and documentation

https://rlpyt.readthedocs.io/en/latest/
