### ISSUE TITLE
Does `CpuWaitResetCollector` collect only one episode in each batch?

### ISSUE THREAD

**Issue by yd-yin** [astooke/rlpyt#186]
It says in `CpuWaitResetCollector` that 
> It waits to reset any environments with completed episodes until after
    the end of collecting the batch, i.e. the ``done`` environment is bypassed
    in remaining timesteps, and zeros are recorded into the batch buffer.

Does it mean that there is always only one episode in each batch? I.e., if batch_B=1, batch_T=500, episode length=1, there will be 1 data and 499 zeros in a batch

**Comment by astooke** [comment]
Yes, that is correct.

**Comment by yd-yin** [comment]
Thanks
