### ISSUE TITLE
GpuSampler gets first actions with all zero observations

### ISSUE THREAD

**Issue by vuoristo** [astooke/rlpyt#20]
https://github.com/astooke/rlpyt/blob/01514b8b2ead41f61e7139431fbb9b08ea07f8d2/rlpyt/samplers/parallel/gpu/action_server.py#L16

All buffers in `agent_inputs` are filled with zeros so the first action is computed with all zeros observation.

**Comment by astooke** [comment]
Thanks, right again!  I think fixed in `DecorrelatingStartCollector` in the lines following:

https://github.com/astooke/rlpyt/blob/f0a190c7efe0c55f61ca78dfd30f8d91e9277b24/rlpyt/samplers/collectors.py#L103

**Comment by vuoristo** [comment]
Your fix was needed but it is not quite enough. I made a pull request for copying observations to the step buffer in `rlpyt/samplers/parallel/gpu/sampler.py:build_step_buffer`. Since this is called with the observation from env.reset, there are no previous actions or rewards to copy.

**Comment by vuoristo** [comment]
A note for anyone who happens to be masking their actions based on an environment supplied action mask. `GpuWaitResetCollector` will compute actions for all environments until all of them are done. The actions for environments that are done, are computed for all zero observations. Therefore, action sampling needs to support all zero action masks, even if they are technically invalid. But yeah, this is probably not a very common issue.

https://github.com/astooke/rlpyt/blob/a92ccc89ffef1d44e5e1dbf3391c22aec14400af/rlpyt/samplers/parallel/gpu/collectors.py#L76

**Comment by vuoristo** [comment]
Btw, the fix in f0a190c7efe0c55f61ca78dfd30f8d91e9277b24 breaks at least `example_3`

```
Traceback (most recent call last):
  File "examples/example_3.py", line 80, in <module>
    n_parallel=args.n_parallel,
  File "examples/example_3.py", line 62, in build_and_train
    runner.train()
  File "/Users/ristovuorio/projects/rlpyt/rlpyt/runners/minibatch_rl.py", line 190, in train
    n_itr = self.startup()
  File "/Users/ristovuorio/projects/rlpyt/rlpyt/runners/minibatch_rl.py", line 61, in startup
    world_size=world_size,
  File "/Users/ristovuorio/projects/rlpyt/rlpyt/samplers/serial/sampler.py", line 65, in initialize
    self.max_decorrelation_steps)
  File "/Users/ristovuorio/projects/rlpyt/rlpyt/samplers/collectors.py", line 104, in start_envs
    self.step_buffer_np.observation[:] = observation
AttributeError: 'NoneType' object has no attribute 'observation'
```

**Comment by astooke** [comment]
Hmm, interesting point:

> Therefore, action sampling needs to support all zero action masks, even if they are technically invalid.

Another thing to do would be to modify the collector loop to insert the appropriate null value: `step.action[b] = env.action_space.null_value()`, and of course make sure the environment's action space has that value defined the way you want.  (I think I made the collector fill in 0's before I settled on the `space.null_value()` interface.)

**Comment by vuoristo** [comment]
Thanks for the ideas!

I found it easiest just to fix my architecture and the action sampling code to not produce nans when the inputs are all zeros.

The original issue was fixed already earlier so closing this now.
