### ISSUE TITLE
Runtime complexity for Rainbow and DQN

### ISSUE THREAD

**Issue by bmazoure** [astooke/rlpyt#29]
Is there any comparison of the running time of this code for Rainbow on Atari against, for example, [https://github.com/Kaixhin/Rainbow](this)?

**Comment by astooke** [comment]
Hi!  I haven't speed tested Rainbow in rlpyt.  But I would expect similar performance to what we reported with Theano in [https://arxiv.org/abs/1803.02811](https://arxiv.org/abs/1803.02811).  There, 2-GPU/10-CPU could finish an Atari run in under 9 hours.  (this is without noisy nets)

Please let us know if you try it!  :)    (could try synchronous and asynchronous runners)

**Comment by bmazoure** [comment]
Thanks for the link, the speed performance seems impressive.
