### ISSUE TITLE
CpuParallel

### ISSUE THREAD

**Issue by kapsl** [astooke/rlpyt#36]
I cannot get the CpuParallel working. What I don't understand at all is that in parallel base we have self._build_parallel_ctrl(n_worker). But then inside this function for barriers n-worker + 1 is taken. And because we have one barrier more than worker I hang at self.ctrl.barrier_out.wait()

**Comment by astooke** [comment]
What is the setup and error you're getting?  Is your setup following the examples?  The +1 in the barrier is for the master process.

**Comment by kapsl** [comment]
I need to dig more into detail. Normally my setup and environment is following the examples and it works like normal environments. At least it works in other RL Frameworks. 
As others said, a bit more code comments would make debugging and understanding much easier.

**Comment by astooke** [comment]
Any news or new questions here? If not, we can close this issue?

**Comment by astooke** [comment]
Hopefully the documentation is a help!  Can still add more code comments, too.
