### ISSUE TITLE
Mixing gaussian and categorical actions?

### ISSUE THREAD

**Issue by w121211** [astooke/rlpyt#39]
By looking at the source code, it seems only allow an agent's actions be either gaussian or categorical?
Since I need the agent to output both gaussian & categorical actions, if this is a feature yet to be implemented, I am happy to help.

**Comment by astooke** [comment]
Hi!  If you need some gaussian actions, and some categorical actions, you can certainly do this!  Simply make a separate action space for each of those, and then make a `Composite` action space which holds both of those.  The action space which the environment exposes should be the composite one.

Hmm now that I'm looking back over things, I don't think we have an example of this up in the repo...I'll make one soon!  But feel free to ask questions in the meantime.

**Comment by astooke** [comment]
Any news or new questions here? If not, we can close this issue?

**Comment by w121211** [comment]
> Hi! If you need some gaussian actions, and some categorical actions, you can certainly do this! Simply make a separate action space for each of those, and then make a `Composite` action space which holds both of those. The action space which the environment exposes should be the composite one.

Thanks for the information. As reading the code, although there is a `Composite` action space for mixing gaussian and categorical actions, the RL algorithms (for example, PPO) may not support the `Composite` action space. Is my understanding correct?

**Comment by astooke** [comment]
Right, one more thing you might need to plug into the algorithm, is to define the distribution class which can give log probabilities for the actions.  If you look inside PPO you'll see it use the `self.agent.distribution` for these parts, so you'd want the agent to have the new distribution.  Then PPO should work fine.

**Comment by astooke** [comment]
Sounds like the question was answered, hope this worked?  If not, please reopen. :)

**Comment by Adithya-MN** [comment]
Hi, @astooke 

I'm trying to use a Composite space with a DQN, but I'm running into this issue - 
```
File "/workspace/algo/src/rlpyt/rlpyt/agents/dqn/dqn_agent.py", line 45, in initialize
    self.distribution = EpsilonGreedy(dim=env_spaces.action.n)
AttributeError: 'Composite' object has no attribute 'n'
```

I assume this is because the algorithm does not currently support the Composite space right now, is that correct?
Also, is there any available list of algorithms that currently have the Composite space supported?
