### ISSUE TITLE
In-line documentation

### ISSUE THREAD

**Issue by juliusfrost** [astooke/rlpyt#41]
I would love to see more in-line documentation, particularly with function docstrings. I think this would accelerate adoption. 
Personally, I prefer sphinx docstrings: [https://pythonhosted.org/an_example_pypi_project/sphinx.html#function-definitions](url)
This allows the added benefit of adding automatic [readthedocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html)

**Comment by carlbalmer** [comment]
I agree with this. I think the most important ones are the __init__ params for sampler and runner (and their subclasses). For example; what does world_size in SerialSampler do?

And as a second priority maybe the __init__ params for algos.

**Comment by astooke** [comment]
Thanks for the feedback, and I agree.  And I've used sphinx for readthedocs in the past and really liked it.  Now that this project is picking up some steam, this is at the top of the to-do list....sorry for the wait!

**Comment by DanielTakeshi** [comment]
I am told that @astooke  is hard at work on this! :)

**Comment by DanielTakeshi** [comment]
Just a quick note, this issue can be closed. https://github.com/astooke/rlpyt/issues/101
