### ISSUE TITLE
logger_context overrides log_dir when rlpyt installed to site-packages

### ISSUE THREAD

**Issue by carlbalmer** [astooke/rlpyt#42]
I have rlpyt installed to site-packages and am using the logger like this:

```
from rlpyt.utils.logging.context import logger_context

 with logger_context(log_dir, run_ID, name, snapshot_mode="last"):
    runner.train()
```

but the `log_dir` passed to `logger_context` is ignored and logs saved in site-packages/data

the code causing the overriding is at utils/logging/context.py line 25
```    
if LOG_DIR != osp.commonpath([exp_dir, LOG_DIR]):
    print(f"logger_context received log_dir outside of {LOG_DIR}: "f"prepending by {LOG_DIR}/local/<yyyymmdd>/")
```
This behavior is unintuitive. I don't understand why it is even there?

**Comment by astooke** [comment]
I usually have this package installed to a directory in my home folder, e.g. `~/code/rlpyt`, as in the readme instructions `pip install -e .`, in which case this log_dir will put all data into the folder `~/code/rlpyt/data` (which is in the gitignore).  You are free to change this as you wish!  :)
