### ISSUE TITLE
get_example_output() calls model without batch dimension

### ISSUE THREAD

**Issue by carlbalmer** [astooke/rlpyt#43]
In `SerialSampler.initialize` the samples buffer `self. samples_pyt` is initialized based on samples obtained by calling `rlpyt.samplers.buffer.get_example_outputs()` (rlpyt/samplers/serial/sampler.py line 36).

The problem is that `get_example_output()` does not add a batch dimension to the inputs passed to `model.forward()`. (e.g. if enviroment observation shape is `(4)` the input to `model.forward()` should be `(1,4,)` but `(4)` is passed to the model by `get_example_output()` )

The pytorch doc states:
> torch.nn only supports mini-batches. The entire torch.nn package only supports inputs that are a mini-batch of samples, and not a single sample.

This means that the models will behave inconsistently. For example `DuelingHeadModel` will ignore the missing batch dimension (e.g. input shape `(4)` output shape `(output_size)`) while `DistributionalDuelingHeadModel` will add a batch dimention to the output (e.g.  input shape `(4)` output shape `(1, output_size, n_atoms)`).

This behavior then causes an error in 
```
rlpyt.utils.tensor.select_at_indexes(indexes, tensor)
assert indexes.shape == tensor.shape[:dim]
```
because of mismatching indexes dimensions (wrongly initialized samples_pyt).

**Comment by astooke** [comment]
Hi!  This is the intended behavior, to call the agent without the batch dimension.  See the models which are associate with the algorithms (e.g. under `models/pg`) where the `forward()` method includes reshaping using the `infer_leading_dims()` and `restore_leading_dims()`.  This is the intended usage.  These other models such as `DuelingHead` are not intended to be used alone as the agent model, but rather as building blocks for that.

Hope that helps!
