### ISSUE TITLE
sample environment for character generation? 

### ISSUE THREAD

**Issue by saikrishna-1996** [astooke/rlpyt#46]
Hey, I am trying to build a custom environment for character generation. (i.e, it should generation one character at each time step to maximize a reward function at the end of episode / sentence). I am taking inspiration from the AtariEnv given in this repo: https://github.com/astooke/rlpyt/blob/master/rlpyt/envs/atari/atari_env.py

But, I am confused as to how I should define `self._observation_space` and `self.obs` so that it's compatible with the rest of the code. Suppose I have 64 characters, my action space would be: `self._action_space = spaces.Discrete(64)`. Can the observation be a string (I tried this but did not work) or just another vector (which represents just the latest action) ? It would be cool if this issue can be resolved, it will be very useful for NLP research! Thanks!

**Comment by astooke** [comment]
Hi!  Thanks for the question, I haven't considered this case before.  Let's see...

For discrete action spaces like this, there is the `IntBox` space, which is 0-dimensional if you don't give it a `shape` input (like in the Atari env), so you could use `self._action_space=spaces.IntBox(low=0, high=64)`.  (And if memory use is an issue, you can use `dtype=np.uint8`.)
The observation and the action need to be numpy arrays, in this case probably integers.  You might want to augment the space or the environment to also hold the conversion between the integers to the human-readable characters.  The infrastructure is set up such that you would need to pass the numpy array as the action into the `env.step(action)`, and then inside the env do whatever conversion.

And yes I the observation needs to be a fixed size.  So if you need variable size, would have to do some padding.

Does this make sense, and help?

**Comment by saikrishna-1996** [comment]
I see, thanks! Yes, it helps! I will try this out and let you know if it works..

**Comment by astooke** [comment]
Any news or new questions here? If not, we can close this issue?

Did it work??

**Comment by astooke** [comment]
closing until further notice :)
