### ISSUE TITLE
Dimensionality of observations in Atari

### ISSUE THREAD

**Issue by bmazoure** [astooke/rlpyt#47]
Typically, the DeepMind preprocessing implies reshaping each observation into stacked `84x84x4`, but in this case, the environment is `80x104x4`. Is there any justification as to why this choice of dimensions? Is reshaping faster because the dimensions are halved?

**Comment by astooke** [comment]
Hi!  Yes that’s exactly it, by using exactly a factor of 2 the downsizing by cv2 was much faster, significantly improving the environment step time.

**Comment by DanielTakeshi** [comment]
@astooke  Thanks for the clarification. Do you know if any of the DeepMind benchmarks or papers used this dimensionality?

**Comment by astooke** [comment]
As far as I know, DM always uses 84x84.  I had originally used that, and never saw a significant difference in learning performance vs 80x104, but I didn't look into it super closely.

**Comment by bmazoure** [comment]
I can confirm that at least on Seaquest and Asteroids, the values of 80x104 reproduce the ones in the C51 paper. Pong converged a little slower for me but this might be due to some hyperparameters.
