### ISSUE TITLE
[NewEnv] Plan to create an env and agent for Pommerman game 

### ISSUE THREAD

**Issue by shenzhun** [astooke/rlpyt#48]
Not sure whether this is a good place to discuss new features, but I can't find another channel(slack, email list etc) to discuss my plan based on rlpyt.

I'm a CS graduate student at USC, my team of 8 graduate students(https://github.com/pommerman) is taking an experimental game class' Applied Machine Learning on Games'(https://web-app.usc.edu/soc/syllabus/20193/30384.pdf). Our goal is to learn and understand more by applying more RL algos on Pommerman. Also, we want to try our best to figure out some insights so that we can take part in the Pommerman Competition (https://www.pommerman.com/) in NIPS 2019 on Nov 22nd.

We learned new RL algos and tried to apply RL lib both on PyTorch and Tensorflow, then we found most of the libs are not modular, and it is hard to apply them on Pommerman without rewriting envs or agents. It was pretty painful for the past 5 weeks. Luckily, I found rlpyt this Wed and it is the RL lib want to use. As there is no env or agent for Pommerman, I want to implement one, any suggestion to kick it off?

**Comment by astooke** [comment]
Sounds great!  Want to email me (email is on the paper) and we can communicate that way, maybe even set up a time to chat?  Some documentation that would be helpful for you doesn't exist yet ;)

**Comment by shenzhun** [comment]
Thanks, email sent. Let's talk more by email.
