### ISSUE TITLE
How does this distinguish from ray's rllib

### ISSUE THREAD

**Issue by kapsl** [astooke/rlpyt#49]
Hi,
how is this library different from Berkeleys ray lib?

**Comment by bmazoure** [comment]
@kapsl  AFAIK this is also by BAIR, but doesn't rely on Ray underneath. I've had issues with Ray Rllib where there was no code for DQN, or the values were drastically lower than in the paper.

**Comment by astooke** [comment]
A main implementation difference is that rlpyt has no built-in distributed code, it's all single-node.  For this case, rlpyt is optimized for performance.  And possibly rlpyt includes some algorithms which aren't in Rllib, and vice versa.  Check out the paper for more discussion :)

**Comment by DanielTakeshi** [comment]
@kapsl  Another shorter explanation is on the BAIR blog:

https://bair.berkeley.edu/blog/2019/09/24/rlpyt/

> Other published research code bases include OpenAI Baselines and Dopamine, both of which are implemented in Tensorflow, and neither of which are optimized to the extent of rlpyt nor contain all three algorithm families. Rllib, built on top of Ray, takes a different approach focused on distributed computing, possibly complicating small experiments. Facebook Horizon offers a subset of algorithms and focuses on applications toward production at scale. In sum, rlpyt provides modular implementations of more algorithms and modular infrastructure for parallelism, making it a distinct toolset supporting a wide range of research uses.

**Comment by astooke** [comment]
Seems like this answered the question well enough :)

**Comment by zlf0625** [comment]
> A main implementation difference is that rlpyt has no built-in distributed code, it's all single-node. For this case, rlpyt is optimized for performance. And possibly rlpyt includes some algorithms which aren't in Rllib, and vice versa. Check out the paper for more discussion :)

Hi,
The implementation looks nice:) I am also interested in that if running only with a single node, is there any significant difference between `Ray` (or its Rllib) and `rlpyt`? For example, I saw both use multi-processing for parallelization and require extra mechanisms to share objects in the memory.
