### ISSUE TITLE
multi-modal observations of different length in one namedarraytuple

### ISSUE THREAD

**Issue by carlbalmer** [astooke/rlpyt#51]
I am trying to pass two input vectors to my agent: a observation vector and a legal action vector. They do not have the same size.

env.py:
```
Observation = namedarraytuple("Observation", ["vectorized_obs", "legal_actions"])
...
def step(self, action):
    ....
   return  EnvStep(Observation(obs, legal_actions), reward, done, env_info)
```

But i get an error in `PrioritizedReplay.__init__`:
```
rlpyt/utils/buffer.py", line 107, in get_leading_dims
    raise ValueError(f"Found mismatched leading dimensions: {contents}")
ValueError: Found mismatched leading dimensions: ((1041,), (38,))
```
The documentation for namedarraytuple mentions:
> contained objects, which must share indexing (__getitem__) behavior

does this mean they have to have the same length?

**Comment by wangwwno1** [comment]
Hello carlbalmer, the `namedarraytuple` require same leading dimensions to be stored into ReplayBuffer. Does this part of code is defined in your environment (Look like a Gym-style Env.)?
If so, just return your `Obsersvation` as a Dict or OrderedDict(recommended) like this:
```
observation = OrderedDict(
        obs=obs,
        legal_actions=legal_actions,
)
return observation, reward, done, env_info
```
The `GymEnvWrapper` will do the rest, hope that helps!
