### ISSUE TITLE
about variable/class/argument naming conventions

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#56]
Hi, this is a great framework, but I found that the variable/class/argument naming styles are very inconsistent, some of them are camel-case(e.g. EnvCls), some of them are words separated by underscores(e.g. cuda_idx), and some of them are mixed style(e.g. run_ID), which seems to be too casual, could you please conform to some code standards like PEP8, I think this will be more friendly to the users, thank you.

**Comment by astooke** [comment]
Hi!  Thanks for noticing the details :)  The EnvCls (EnvironmentClass) is camel case because as a hint that this should be a class object (or factory function), most are variables with lowercase and underscore convention.  Yes I see the run_ID is an anomaly which could be run_id, an old leftover.

**Comment by codelast** [comment]
Thanks & hope to see coding style standardization in the future release.
