### ISSUE TITLE
'bootstrap_timelimit' in q function policy gradient algorithms

### ISSUE THREAD

**Issue by renqibing** [astooke/rlpyt#57]
I quote the explanation about 'bootstrap timelimit' from the author for possible readers who have similar questions. 

> By the way, can you tell me what does bootstrap_timelimit do? Does it correspond with pretraining? I see all of q function policy gradient algorithms set it as true.

Yes this is from the original SAC implementation, it makes the algorithm use the next Q value in the Q-learning target when the episodes ends due to timeout.  Normally, when an episode is `done`, the next Q value would not be used, only the reward.  Intuitively, the time limit is an arbitrary implementation decision, but the agent should learn as if it can run forever.  Not to do with pretraining.  Try it with and without, it makes a difference on e.g. HalfCheetah. (good idea to ask in separate thread in the future, so others can find it  :)

_Originally posted by @astooke in https://github.com/astooke/rlpyt/issues/50#issuecomment-546201928_

**Comment by ritalaezza** [comment]
Sorry to reopen this thread, but I am curious if this detail was reported in any of the literature? I cannot find any mention of it in the SAC paper. I did notice a huge improvement in my application when using it and would like to cite the appropriate work.

**Comment by astooke** [comment]
Hmm I just took a look back through the original SAC code which I was sure had it...and I don't see it there.  I probably first heard it from personal correspondence.  I'm sure I've seen it in code somewhere...

**Comment by ritalaezza** [comment]
I've been talking to a colleague about this and he pointed me to this work on [Time Limits in RL]( https://sites.google.com/view/time-limits-in-rl), by Pardo et al.
