### ISSUE TITLE
UnboundLocalError in replays/sequence/prioritized.py

### ISSUE THREAD

**Issue by wangwwno1** [astooke/rlpyt#58]
Hello, this part of code may raise UnboundLocalError if self.rnn_state_interval <= 1
UnboundLocalError: local variable 'T_idxs' referenced before assignment
https://github.com/astooke/rlpyt/blob/ba824f18f8598521ea4eb9f06e4f9fb129eb599a/rlpyt/replays/sequence/prioritized.py#L67-L72

I post a PR to fix this by change `tree_T_idxs` to `T_idxs`, feel free to check it out : )

**Comment by wangwwno1** [comment]
BTW, there will be an ZeroDivisionError if self.rnn_state_interval = 0
https://github.com/astooke/rlpyt/blob/ba824f18f8598521ea4eb9f06e4f9fb129eb599a/rlpyt/replays/sequence/prioritized.py#L28-L31
Look like the division should be max(1, self.rnn_state_interval)?

**Comment by astooke** [comment]
I think fixed in that PR.  If not, please re-open!
