### ISSUE TITLE
Where does horizon=27000 come from in atari_env.py ?

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#60]
Hi, in file atari_env.py:

> class AtariEnv(Env):
> 
>     def __init__(self,
>                  game="pong",
>                  frame_skip=4,  # Frames per step (>=1).
>                  num_img_obs=4,  # Number of (past) frames in observation (>=1).
>                  clip_reward=True,
>                  episodic_lives=True,
>                  max_start_noops=30,
>                  repeat_action_probability=0.,
>                  horizon=27000,
>                  ):

I want to ask that why it's 27000? I mean is this just an arbitrary value and can be 28000, 29000, or any value similar to it?
Thank U.

**Comment by astooke** [comment]
Oh yes that's sort of an informal research standard....many of the works using Atari benchmark used that number.  But you could change it without breaking anything. :)
