### ISSUE TITLE
IndexError in SumTree.sample when unique=True

### ISSUE THREAD

**Issue by wangwwno1** [astooke/rlpyt#61]
An IndexError will raise when passing `True` to attribute `unique`.
https://github.com/astooke/rlpyt/blob/ba824f18f8598521ea4eb9f06e4f9fb129eb599a/rlpyt/replays/sum_tree.py#L95-L112
This error is caused by the return of self.find - it return two array called `tree_idxes` and `scaled random_values`.
https://github.com/astooke/rlpyt/blob/4057c6774a0eec2875f3c049f0b7c9c64ea401aa/rlpyt/replays/sum_tree.py#L199-L210
Things are normal when `unique` is False, however, if user pass `unique=True`, the input of np.unique will become a tuple `(tree_idx, scaled_random_values)` with dtype as `(np.int64, np.float)`
https://github.com/astooke/rlpyt/blob/ba824f18f8598521ea4eb9f06e4f9fb129eb599a/rlpyt/replays/sum_tree.py#L99
Which returns the unique array of **both** `tree_idx` and `scaled_random_values`, not `tree_idx`.

This bug is fixed in PR #59 
https://github.com/astooke/rlpyt/blob/4057c6774a0eec2875f3c049f0b7c9c64ea401aa/rlpyt/replays/sum_tree.py#L95-L117

**Comment by astooke** [comment]
I think you fixed this in the PR, thanks!  If not, please re-open.  :)
