### ISSUE TITLE
Are policy weights saved? 

### ISSUE THREAD

**Issue by thomasweng15** [astooke/rlpyt#66]
I am unable to determine from the whitepaper and code whether the policy weights are saved. I'd like to be able to run the agent after training. They don't seem to be saved in the logging directory. Is there another location or am I missing something? Thank you very much for your help!

**Comment by astooke** [comment]
Hi!  Yeah I think this is missing from the examples.  You can pass the kwarg `snapshot_mode` into the `logger_context()`, and that will set it in the logger.  For example, `snapshot_mode=last` will overwrite with the latest learned agent each time the parameters are recorded.  They will go into the experiment folder in a file like `params.pkl`, which is different from `params.json`, which holds the settings.  Sorry that's kind of hidden!

**Comment by thomasweng15** [comment]
Thanks!

**Comment by DanielTakeshi** [comment]
It's worth pointing out that the process of overwriting with the latest learned agent happens each time the *logger* is recorded (though the logger is referred to having "parameters" in `utils/logging/context.py` I normally think of "parameters" as from the policy network itself). It's easiest to see this with `examples/example_1.py` and then adjusting the value of `log_interval_steps` in the `MinibatchRlEval` (or `MinibatchRl`) class. Both call their superclass logger which saves snapshots if we are past some iteration threshold:

https://github.com/astooke/rlpyt/blob/75e96cda433626868fd2a30058be67b99bbad810/rlpyt/runners/minibatch_rl.py#L126-L131

which in turn calls this code just above:

https://github.com/astooke/rlpyt/blob/75e96cda433626868fd2a30058be67b99bbad810/rlpyt/runners/minibatch_rl.py#L105-L117

The logger's method can be found here:

https://github.com/astooke/rlpyt/blob/75e96cda433626868fd2a30058be67b99bbad810/rlpyt/utils/logging/logger.py#L320-L336

which finally does `torch.save` (scroll down a bit) and also shows the different options that are available to the user: all, last, gap, or none. Pick whichever one applies best for your use case. For the snapshot gap, you can set the gap by calling this:

https://github.com/astooke/rlpyt/blob/75e96cda433626868fd2a30058be67b99bbad810/rlpyt/utils/logging/logger.py#L161-L163

You can call that just before the `with logger_context` in the example scripts as long as you import the logger.

One possible change I would make is to add `str(itr).zfill(8)` or something like that to the parameter file name (currently `itr_{}.pkl`) which would handle my OCD in getting numbers arranged in alphabetical order with the appropriate leading zeros padded.

**Comment by astooke** [comment]
@DanielTakeshi yesss thanks for setting out those tips, these options are not well exposed in the code examples, or the code itself.

> One possible change I would make is to add str(itr).zfill(8) 

Yes, this is a great idea!  Otherwise it is a pain to try to sort through those files in any order.
