### ISSUE TITLE
TypeError in loading optimizer parameters in ddpg

### ISSUE THREAD

**Issue by renqibing** [astooke/rlpyt#73]
In the function optim_state_dict( ) in rlpyt/algos/ddpg.py, parameters of optimizers of mu network cannot be saved successfully because it only returns the function method of state_dict without "( )".

**Comment by codelast** [comment]
Agree.

**Comment by astooke** [comment]
Whoops, good catch!  Will fix soon :)

**Comment by astooke** [comment]
OK fixed!
