### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by AlexanderKoch-Koch** [astooke/rlpyt#77]
Is there a reason that there is no option to enable tensorboard logging?
I have seen that the logger has variables to save the summary writer and directory. But the there is no parameter for the runner classes to use it.

**Comment by codelast** [comment]
Using TensorBoard as the visualization tool? rlpyt uses viskit as its visualization tool.

**Comment by astooke** [comment]
Hi!   I haven't used tensorboard with rlpyt before, always viskit.  But does it seem like it would be helpful and easy to incorporate tensorboard into the runner+logger?  Anyone else used it?

**Comment by AlexanderKoch-Koch** [comment]
Yes, it's not difficult. I have created a pull request, so that you can see the changes I made. I had to add some code to set the current iteration in the logger. Maybe this should replace the logger.prefix call. And if you want to enable tensorboard logging you just have to set the tf_summary_writer in the logger. This could maybe be added to the logger_context.

**Comment by astooke** [comment]
OK I think this has all been incorporated!  If it's not working please re-open :)
