### ISSUE TITLE
about nan in training process

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#78]
Hi, I may not dig into the code deep enough so I have a question when I see the output logs in the training process, e.g. for example_1, when the training process starts, in the first few iterations(not sure how many, fixed number or not),  following data are all "nan":

> lossAverage               nan
> lossStd                   nan
> lossMedian                nan
> lossMin                   nan
> lossMax                   nan
> gradNormAverage           nan
> gradNormStd               nan
> gradNormMedian            nan
> gradNormMin               nan
> gradNormMax               nan
> tdAbsErrAverage           nan
> tdAbsErrStd               nan
> tdAbsErrMedian            nan
> tdAbsErrMin               nan
> tdAbsErrMax               nan

And after some iterations these data become meaningful values:

> lossAverage                  0.011436
> lossStd                      0.0126516
> lossMedian                   0.014712
> lossMin                      4.32141e-05
> lossMax                      0.0600907
> gradNormAverage              0.0288534
> gradNormStd                  0.018582
> gradNormMedian               0.028906
> gradNormMin                  0.00462809
> gradNormMax                  0.113463
> tdAbsErrAverage              0.0388293
> tdAbsErrStd                  0.134632
> tdAbsErrMedian               0.0192974
> tdAbsErrMin                  5.59241e-05
> tdAbsErrMax                  1

My question is: what is the data updating mechanism behind this? I mean when will be "nan" turned into numbers? Is it after some fixed number iterations that the changing happens, or it's depending on the situation of a specific training process?
Thanks.

**Comment by AlexanderKoch-Koch** [comment]
The algo has a min_steps_learn argument. This determines after how many steps the algorithm will begin learning. So only after min_steps_learn has the algorithm meaningful values for loss etc. Before that it is just returns nan.

**Comment by codelast** [comment]
@AlexanderKoch-Koch Thanks a lot.

**Comment by astooke** [comment]
Correct, when there is no data stored into a field, the logger records a nan.   Nothing to worry about :)
