### ISSUE TITLE
example_3 import error

### ISSUE THREAD

**Issue by Coolnesss** [astooke/rlpyt#8]
Trying to run `example_3.py` with `sample_mode="cpu"`, getting
```bash
$ python example_3.py --sample_mode cpu
```
```python
Traceback (most recent call last):
  File "example_3.py", line 80, in <module>
    n_parallel=args.n_parallel,
  File "example_3.py", line 30, in build_and_train
    Sampler = CpuParallelSampler
NameError: name 'CpuParallelSampler' is not defined
```
I guess https://github.com/astooke/rlpyt/blob/master/examples/example_3.py#L30 should be
```
Sampler = CpuSampler
```
and https://github.com/astooke/rlpyt/blob/master/examples/example_3.py#L33
```
Sampler = GpuSampler
```

but not entirely sure since CpuParallelSampler does appear in some code

**Comment by astooke** [comment]
Yes that's right, thanks!  Have fixed these.

CpuParallelSampler was an old name I should go through and clean up...the experiments folder has many old scripts in it.

**Comment by Coolnesss** [comment]
Thanks, looks fixed!
