### ISSUE TITLE
a question about the _action_set of "pong" game

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#83]
When running example_1.py and set a break point in atari_env.py, we can see that self._action_set has a value of(a ndarray):

> [ 0  1  3  4 11 12]

So what do these values mean? Seems that "pong" game should be a continuous control problem, not a discrete one, so why its action space is discrete?

**Comment by AlexanderKoch-Koch** [comment]
As far as I know, all Atari games have a discrete action space. I think in pong it's just up and down

**Comment by codelast** [comment]
@AlexanderKoch-Koch  Thank you.
OK, so may be an action represents "moving up" just means moving upward one pixel ( or some fixed number of pixels), so it doesn't need a float number to control "how far should it move upward", right? If it's like this, then I understand.
But why "pong" game needs 6 actions, if it's just up & down?

**Comment by andreacini** [comment]
I think this is relate to the atari emulator, in some games there are action (buttons) that are basically useless.

Btw, you can check the meaning of each action doing something like this:
```
>>> gym.make('Pong-v0').unwrapped.get_action_meanings()
['NOOP', 'FIRE', 'RIGHT', 'LEFT', 'RIGHTFIRE', 'LEFTFIRE']
```

**Comment by codelast** [comment]
@andreacini Thanks a lot.

**Comment by codelast** [comment]
@andreacini Thanks a lot.

**Comment by DanielTakeshi** [comment]
@codelast  the actions are also shown here:

https://github.com/astooke/rlpyt/blob/d797dd8835a91a7b2902563a097c83ed7c8d3e92/rlpyt/envs/atari/atari_env.py#L223-L242
