### ISSUE TITLE
Undefined name: 'act_waitrs_pair' in gpu/action_server.py

### ISSUE THREAD

**Issue by cclauss** [astooke/rlpyt#9]
https://github.com/astooke/rlpyt/blob/master/rlpyt/samplers/parallel/gpu/action_server.py#L233

[flake8](http://flake8.pycqa.org) testing of https://github.com/astooke/rlpyt on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./rlpyt/samplers/base.py:38:36: F821 undefined name 'Samples'
        raise NotImplementedError  # type: Samples
                                   ^
./rlpyt/samplers/parallel/gpu/action_server.py:233:26: F821 undefined name 'act_waitrs_pair'
                for w in act_waitrs_pair[1]:
                         ^
./rlpyt/samplers/async_/alternating_sampler.py:59:13: F821 undefined name 'logger'
            logger.log("WARNING: affinity requested different number of "
            ^
./rlpyt/samplers/async_/action_server.py:156:18: F821 undefined name 'act_ready'
        for w in act_ready:
                 ^
./rlpyt/utils/logging/tabulate.py:494:25: F821 undefined name 'zip_longest'
            rows = list(zip_longest(*list(tabular_data.values())))  # columns have to be transposed
                        ^
./examples/example_3.py:30:19: F821 undefined name 'CpuParallelSampler'
        Sampler = CpuParallelSampler
                  ^
./examples/example_3.py:33:19: F821 undefined name 'GpuParallelSampler'
        Sampler = GpuParallelSampler
                  ^
7     F821 undefined name 'CpuParallelSampler'
7
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by astooke** [comment]
Thanks for the test!   Fixed all these  :)

**Comment by cclauss** [comment]
Nice!  The first one on the list still is not resolved.  It is saying that the type checker might get confused because __Sample__ is not defined it that context.

**Comment by astooke** [comment]
Oh right, OK I'll clean up that comment next round :)  Thnx again!
