### ISSUE TITLE
under parallel training mode, is statistic such as "StepsPerSecond" the overall data ?

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#90]
Hi, after start training process, the screen will continuously output statistic data, e.g. 

> 2019-11-25 15:41:39.993249  | CumUpdates          14820
> 2019-11-25 15:41:39.993340  | StepsPerSecond       1832.32
> 2019-11-25 15:41:39.993455  | UpdatesPerSecond       36.6464
> 2019-11-25 15:41:39.993561  | ReplayRatio            25.6
> 2019-11-25 15:41:39.993651  | CumReplayRatio         23.9818

These are the overall data of all the workers, right ? 
For example, "StepsPerSecond  1832.32" means that all workers together can move 1832.32 steps forward per second totally, right ?

**Comment by astooke** [comment]
Yes, that is correct.  Even in the case of multi-GPU, it counts all the workers from all processes.

**Comment by codelast** [comment]
Thanks.
