### ISSUE TITLE
Can we use multiple GPUs for GPU sampler?

### ISSUE THREAD

**Issue by kaixin96** [astooke/rlpyt#91]
It seems current gpu sampler only supports one gpu, right? I am thinking about using multiple GPUs to accelerate the sampling.

Thank you.

**Comment by astooke** [comment]
Yes, that is right, the gpu sampler only supports one gpu.

You can use the SyncRl runner to go to multi-GPU, and it will replicate the whole algorithm-sampler stack on each GPU (with the CPU cores divided evenly between GPUs).  So this yields multi-GPU sampling and also multi-GPU training.  Each gradient is all-reduced across GPUs, so the math all works out the same as single-GPU.  See if that works for you?

As an aside, the asynchronous sampler can go multi-GPU, and the optimizer in that case can stay single-GPU.  But that's a much more complicated setup.

**Comment by kaixin96** [comment]
Thanks for you reply. I think SyncRL is what I want.
