### ISSUE TITLE
some explanation on BaseAgent.shared_model ?

### ISSUE THREAD

**Issue by codelast** [astooke/rlpyt#94]
Hi, could anyone please give some brief explanation on the functionality of self.shared_model in class BaseAgent under CPU parallel mode ?

In function BaseAgent.initialize(), I see the comments:

> In this default setup, self.model is treated as the model needed for action selection, so it is the only one
> shared with workers.

This confuse me a little, so if we don't talk about other modes(async, gpu), is self.shared_model necessary under the CPU parallel mode ?
Thank you.

**Comment by astooke** [comment]
Yes, good question.   Check out the "docs" branch...it's under construction, but that piece is in there, documentation in the method.  :)

https://github.com/astooke/rlpyt/blob/fe6d27263b48a374a47830efb69f40842d70be65/rlpyt/agents/base.py#L64

**Comment by codelast** [comment]
@astooke I read the doc, and could you please confirm that whether my understanding is right:
under CPU parallel mode(non-async, non-GPU), it's no need to invoke self.agent.sync_shared_memory() in function CpuSampler.obtain_samples() and CpuSampler.evaluate_agent():

>     def obtain_samples(self, itr):
>         self.agent.sync_shared_memory()  # New weights in workers, if needed.
>         return super().obtain_samples(itr)
> 
>     def evaluate_agent(self, itr):
>         self.agent.sync_shared_memory()
>         return super().evaluate_agent(itr)

Because in BaseAgent, the self.shared_model is only meaningful in 2 places:
(1) def initialize():

>         if share_memory:
>             self.model.share_memory()
>             # Store the shared_model (CPU) under a separate name, in case the
>             # model gets moved to GPU later:
>             self.shared_model = self.model

in this situation, it's just an assignment to self.shared_model, not usage.

(2) def to_device():

>         if cuda_idx is None:
>             return
>         if self.shared_model is not None:
>             self.model = self.ModelCls(**self.env_model_kwargs,
>                 **self.model_kwargs)
>             self.model.load_state_dict(self.shared_model.state_dict())

in this situation, cuda_idx is None(because it's CPU parallel mode), so the self.shared_model is not reachable.

And all other codes using self.shared_model are async-mode related, so I think in class CpuSampler, it's no need to invoke self.agent.sync_shared_memory() at all.

Am I right?

**Comment by astooke** [comment]
Yes, that is correct, because in CPU parallel mode, there is actually only one model, and it is already the shared one.

**Comment by codelast** [comment]
Thanks a lot!
