### ISSUE TITLE
What is the minimum python version this codebase requires?

### ISSUE THREAD

**Issue by ZiwenZhuang** [astooke/rlpyt#97]
Hi, I am working on bringing in meta-RL into this codebase and re-implementing PEARL here. Since many people are using dennisl88's [rand_param_envs](https://github.com/dennisl88/rand_param_envs/tree/4d1529d61ca0d65ed4bd9207b108d4a4662a4da0), I found that it seems not supporting Python 3.7, but Python 3.5 or Python 3.6.
Could you give me some advice about it?
Is Python 3.6 OK for this codebase as I found out that f-string is only available after Python 3.6?

**Comment by codelast** [comment]
I'm using Python 3.6.9 and it's totally fine with rlpyt.
